### ISSUE TITLE
Illegal character(pipe | ) in two schema names (twilio_api_v2010.yaml)

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#10]
Schema name contain pipe( | ) character, which is not allowed.

API spec version 1.4.0 - twilio_api_v2010.yaml
line 868 - api.v2010.account.call.call_notification|instance:
line 2289 - api.v2010.account.notification|instance:

```
 api.v2010.account.call.call_notification|instance:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34 
```

``` 
api.v2010.account.notification|instance:
      properties:
        account_sid:
          maxLength: 34
          minLength: 34
```
