### ISSUE TITLE
twilio_api_v2010.yaml   Some endpoints and/or parameters are missing descriptions

### ISSUE THREAD

**Issue by balucha** [twilio/twilio-oai#13]
### Issue Summary
https://github.com/twilio/twilio-oai/blob/main/spec/yaml/twilio_api_v2010.yaml

e.g. endpoint on line 18915 and its parameters are missing descriptions

```
/2010-04-01/Accounts/{AccountSid}/SigningKeys/{Sid}.json:
    delete:
      description: ''
      parameters:
      - description: ''
        in: path
        name: AccountSid
        required: true
        schema:
          maxLength: 34
          minLength: 34
          pattern: ^AC[0-9a-fA-F]{32}$
          type: string
      - description: ''
        in: path
        name: Sid
...
```
